apiVersion: cluster.redpanda.com/v1alpha1
kind: Topic
metadata:
  name: twitch-chat
spec:
  partitions: 3
  replicationFactor: 3
  kafkaApiSpec:
    brokers:
      - "redpanda-0.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-1.redpanda.redpanda.svc.cluster.local:9093"
      - "redpanda-2.redpanda.redpanda.svc.cluster.local:9093"