apiVersion: v1
kind: Pod
metadata:
    name: python-container
spec:
    containers:
        - name: python
          image: python:3.11
          command: ['/bin/sh']
          args: ['-c', 'while true; do sleep 30; done']
