---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
    name: simple-hive
spec:
    image:
        productVersion: 3.1.3
        stackableVersion: 23.7.0
    clusterConfig:
        database:
            connString: jdbc:postgresql://postgresql:5432/hive
            user: hive
            password: hive
            dbType: postgres
        hdfs:
            nameNodeUri: 'hdfs://simple-hdfs-namenode-default-1.default:8020'
            configMap: simple-hdfs
    metastore:
        roleGroups:
            default:
                replicas: 1
