---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCluster
metadata:
    name: trino
spec:
    image:
        productVersion: '414'
        stackableVersion: '23.7.0'
    clusterConfig:
        catalogLabelSelector:
            matchLabels:
                trino: trino
    coordinators:
        config:
            resources:
                cpu:
                    min: 200m
                    max: 1000m
                memory:
                    limit: 1Gi
        roleGroups:
            default:
                replicas: 1
    workers:
        config:
            resources:
                cpu:
                    min: 200m
                    max: 1000m
                memory:
                    limit: 1Gi
        roleGroups:
            default:
                replicas: 1
---
apiVersion: trino.stackable.tech/v1alpha1
kind: TrinoCatalog
metadata:
    name: hive
    labels:
        trino: trino
spec:
    connector:
        hive:
            metastore:
                configMap: simple-hive
            s3:
                reference: minio
            hdfs:
                configMap: simple-hdfs
    configOverrides:
        hive.s3.endpoint: http://minio:9000
