apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    external:
      domain: customredpandadomain.local
    statefulset:
      replicas: 3
      initContainers:
        setDataDirOwnership:
          enabled: true
    tls:
      enabled: false
