apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
spec:
  chartRef: {}
  clusterSpec:
    resources:
      cpu:
        cores: 500m
      memory:
        enable_memory_locking: false
        container:
          max: 2Gi
    tls:
      enabled: false